services:
  python-service:
    image: python:3.10
    container_name: python-fastapi
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    # command: >
    #   sh -c "
    #   pip install --no-cache-dir fastapi uvicorn redis &&
    #   uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - redis
      - ollama

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    volumes: 
      - ./redis-volume:/data 
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ./ollama-volume:/root/.ollama
    ports:
      - "1337:11434"
