services:
  python-service:
    image: vector-gateway
    container_name: fastapi
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama
      - redis
      - python-rq-worker

  python-rq-worker:
    image: vector-gateway
    container_name: rq-worker
    command: rq worker --url redis://redis-server:6379 default
    volumes:
      - ./src:/app
    depends_on:
      - redis
      - ollama

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    volumes: 
      - ./redis-volume:/data 
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ./ollama-volume:/root/.ollama
    ports:
      - "1337:11434"
