services:
  python-service:
    image: vector-gateway
    container_name: python-fastapi
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    volumes: 
      - ./redis-volume:/data 
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ./ollama-volume:/root/.ollama
    ports:
      - "1337:11434"
